// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtMPp1EePUDp-z7iBQsoziuMwlfW4PjHk',
    appId: '1:521783456338:web:49a6f9159ca64e4e4ea58b',
    messagingSenderId: '521783456338',
    projectId: 'looooja-f6974',
    authDomain: 'looooja-f6974.firebaseapp.com',
    storageBucket: 'looooja-f6974.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqB1EZoZn7SKLEOlP8HKCBLDip9JxGZSQ',
    appId: '1:521783456338:android:94cb4acf635a61184ea58b',
    messagingSenderId: '521783456338',
    projectId: 'looooja-f6974',
    storageBucket: 'looooja-f6974.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjKGix1lJMrUoyCPdiITm2RypWROqgYwc',
    appId: '1:521783456338:ios:fe4dd5c4829189574ea58b',
    messagingSenderId: '521783456338',
    projectId: 'looooja-f6974',
    storageBucket: 'looooja-f6974.appspot.com',
    iosBundleId: 'br.com.dtec.loja.minimalstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjKGix1lJMrUoyCPdiITm2RypWROqgYwc',
    appId: '1:521783456338:ios:fe4dd5c4829189574ea58b',
    messagingSenderId: '521783456338',
    projectId: 'looooja-f6974',
    storageBucket: 'looooja-f6974.appspot.com',
    iosBundleId: 'br.com.dtec.loja.minimalstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtMPp1EePUDp-z7iBQsoziuMwlfW4PjHk',
    appId: '1:521783456338:web:f994be8b11033bdc4ea58b',
    messagingSenderId: '521783456338',
    projectId: 'looooja-f6974',
    authDomain: 'looooja-f6974.firebaseapp.com',
    storageBucket: 'looooja-f6974.appspot.com',
  );
}
